digito = input("digite algo: ")
print("o tipo primario desse valor é {}".format(type(digito)))
print("só tem espaços? {}".format(digito.isspace()))
print("é um numero? {}".format(digito.isnumeric()))
print("é alfabetico? {}".format(digito.isalpha()))
print("é alphanumerico? {}".format(digito.isalnum()))
print("está em maiusculas? {}".format(digito.isupper()))
print("está em minusculas? {}".format(digito.islower()))
print("é capitalizada? {}".format(digito.istitle()))
